spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-math-aqw8ex5x.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        # 물리적 네이밍 전략을 최신 표준으로 변경
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  file:
    upload-dir: /temp/uploads/

ai-server:
  api-key: ${AI_SERVER_API_KEY}

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: audio-files
    cdn-base-url: ${CDN_BASE_URL}
