spring:
  datasource:
    url: jdbc:mysql://team4-db.mysql.database.azure.com:3306/team4_db?serverTimezone=Asia/Seoul&useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
    username: team4root
    password: ${AZURE_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true